import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { listDeveloperIssues, updateDeveloperIssue } from '../api';
import { useProducts } from '../hooks';
import type { DeveloperIssue, IssueStatus } from '../types';
import PageHeader from '../components/PageHeader'; import ErrorBox from '../components/ErrorBox'; import Spinner from '../components/Spinner';
const statusOptions:IssueStatus[]=['pending','in_progress','resolved'];
export default function DeveloperIssuesPage(){const {t}=useTranslation();const products=useProducts(); const [productId,setProductId]=useState<number|''>(''); const [items,setItems]=useState<DeveloperIssue[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [open,setOpen]=useState<number|null>(null);
  useEffect(()=>{if(productId===''&&products.data?.length)setProductId(products.data[0].id)},[products.data,productId]);
  useEffect(()=>{if(productId==='')return;setLoading(true);listDeveloperIssues(productId).then(setItems).catch((e)=>setError(e.message)).finally(()=>setLoading(false))},[productId]);
  const change=async(id:number,status:IssueStatus)=>{try{const updated=await updateDeveloperIssue(id,status);setItems((all)=>all.map((x)=>x.id===id?updated:x))}catch(e:any){setError(e.message)}};
  return <div><PageHeader title={t('developer.issues.title')} desc={t('developer.issues.desc')}/>{error&&<ErrorBox message={error}/>}<select className="w-full md:w-72 border rounded-md px-3 py-2 text-sm mb-5" value={productId} onChange={(e)=>setProductId(Number(e.target.value))}>{(products.data??[]).map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{loading?<Spinner/>:<div className="space-y-3">{items.length===0?<section className="bg-white border rounded-xl p-6 text-sm text-gray-500">{t('developer.issues.empty')}</section>:items.map((item)=><article key={item.id} className="issue-card"><div className="issue-summary"><span className={`risk-pill ${item.risk_level}`}>{t(`common.status.${item.risk_level}`)}</span><div><h2>{item.title}</h2><p>{t('developer.issues.source',{source:item.source})}</p></div><select value={item.status} onChange={(e)=>change(item.id,e.target.value as IssueStatus)}>{statusOptions.map((v)=><option key={v} value={v}>{t(`developer.issues.status.${v}`)}</option>)}</select><button onClick={()=>setOpen(open===item.id?null:item.id)}>{t('developer.issues.fixIt')}</button></div>{open===item.id&&<div className="fix-panel"><div><b>{t('developer.issues.why')}</b><p>{item.why}</p></div><div><b>{t('developer.issues.fixIt')}</b><p>{item.fix}</p></div>{item.recommended_text&&<div><b>{t('developer.issues.recommendedText')}</b><p>{item.recommended_text}</p></div>}{item.placement&&<div><b>{t('developer.issues.placement')}</b><p>{item.placement}</p></div>}</div>}</article>)}</div>}</div>}
