# -*- coding: utf-8 -*-
"""行业预设画像。

在问卷页选择行业后一键加载该行业的典型答案，用户再按实际情况微调。
预设只填写典型字段，其余字段由 questionnaire.normalize_answers 补默认值。
"""

PRESETS = {
    "自定义填写": {},
    "电商类 App": {
        "collect_personal": True,
        "data_types": ["姓名/身份信息", "手机号/邮箱", "设备标识符"],
        "collect_sensitive": True,
        "sensitive_types": ["金融账户", "精确位置"],
        "sensitive_consent": False,
        "minors_under_14": False,
        "storage_location": "中国境内",
        "encrypt_storage": True,
        "access_control": True,
        "breach_plan": False,
        "retention_defined": False,
        "share_third_party": True,
        "sdk_disclosed": False,
        "third_party_agreement": True,
        "right_access": True,
        "right_delete": True,
        "right_withdraw": False,
        "privacy_policy": True,
        "policy_updated": True,
        "consent_popup": True,
        "dau_scale": "1-10万",
        "industry": "电商",
        "eu_users": False,
    },
    "社交类 App": {
        "collect_personal": True,
        "data_types": ["手机号/邮箱", "设备标识符", "日志/行为数据", "通讯录/相册"],
        "collect_sensitive": True,
        "sensitive_types": ["精确位置"],
        "sensitive_consent": False,
        "minors_under_14": True,
        "guardian_consent": False,
        "storage_location": "中国境内",
        "encrypt_storage": True,
        "access_control": False,
        "breach_plan": False,
        "retention_defined": False,
        "share_third_party": True,
        "sdk_disclosed": True,
        "third_party_agreement": False,
        "right_access": True,
        "right_delete": False,
        "right_withdraw": False,
        "privacy_policy": True,
        "policy_updated": False,
        "consent_popup": True,
        "dau_scale": "10万+",
        "industry": "社交",
        "eu_users": False,
    },
    "教育类 App（K12）": {
        "collect_personal": True,
        "data_types": ["姓名/身份信息", "手机号/邮箱", "日志/行为数据"],
        "collect_sensitive": False,
        "minors_under_14": True,
        "guardian_consent": False,
        "storage_location": "中国境内",
        "encrypt_storage": False,
        "access_control": False,
        "breach_plan": False,
        "retention_defined": False,
        "share_third_party": True,
        "sdk_disclosed": False,
        "third_party_agreement": False,
        "right_access": False,
        "right_delete": False,
        "right_withdraw": False,
        "privacy_policy": True,
        "policy_updated": False,
        "consent_popup": False,
        "dau_scale": "1-10万",
        "industry": "教育",
        "eu_users": False,
    },
    "医疗健康类 App": {
        "collect_personal": True,
        "data_types": ["姓名/身份信息", "手机号/邮箱", "设备标识符"],
        "collect_sensitive": True,
        "sensitive_types": ["健康数据", "生物识别"],
        "sensitive_consent": True,
        "minors_under_14": False,
        "storage_location": "中国境内",
        "encrypt_storage": True,
        "access_control": True,
        "breach_plan": True,
        "retention_defined": True,
        "share_third_party": True,
        "sdk_disclosed": True,
        "third_party_agreement": True,
        "right_access": True,
        "right_delete": True,
        "right_withdraw": True,
        "privacy_policy": True,
        "policy_updated": True,
        "consent_popup": True,
        "dau_scale": "1-10万",
        "industry": "医疗健康",
        "eu_users": False,
    },
    "出海工具类 App（面向欧盟）": {
        "collect_personal": True,
        "data_types": ["设备标识符", "日志/行为数据"],
        "collect_sensitive": False,
        "minors_under_14": False,
        "storage_location": "跨境传输到中国境外",
        "cross_border_measure": "无合规措施",
        "encrypt_storage": True,
        "access_control": False,
        "breach_plan": False,
        "retention_defined": False,
        "share_third_party": True,
        "sdk_disclosed": True,
        "third_party_agreement": False,
        "right_access": False,
        "right_delete": False,
        "right_withdraw": False,
        "privacy_policy": True,
        "policy_updated": True,
        "consent_popup": True,
        "dau_scale": "10万+",
        "industry": "通用",
        "eu_users": True,
    },
    "独立开发者小工具": {
        "collect_personal": False,
        "collect_sensitive": False,
        "minors_under_14": False,
        "storage_location": "中国境内",
        "encrypt_storage": False,
        "access_control": False,
        "breach_plan": False,
        "retention_defined": False,
        "share_third_party": False,
        "right_access": False,
        "right_delete": False,
        "right_withdraw": False,
        "privacy_policy": False,
        "consent_popup": False,
        "dau_scale": "<1万",
        "industry": "通用",
        "eu_users": False,
    },
}
