import { NavLink, Outlet, useLocation } from 'react-router-dom';
type Mode = 'business' | 'developer';
const businessNav = [{ section: '总览', items: [{ to: '/business', label: '今日关注' }] }, { section: '企业管理', items: [{ to: '/business/company', label: '企业画像' }, { to: '/business/products', label: '产品合规护照' }] }, { section: '合规管理', items: [{ to: '/business/risks', label: '风险中心' }, { to: '/business/check', label: '合规检查' }, { to: '/business/impact', label: '影响分析' }] }, { section: '整改执行', items: [{ to: '/business/actions', label: '整改任务' }] }, { section: '法规情报', items: [{ to: '/business/regulations', label: '法规中心' }] }];
const developerNav = [{ section: '首页', items: [{ to: '/developer', label: '首页' }] }, { section: '检查', items: [{ to: '/developer/check', label: '快速合规检查' }, { to: '/developer/policy-check', label: '隐私政策检查' }] }, { section: '生成', items: [{ to: '/developer/policy-generator', label: '隐私政策生成' }] }, { section: '参考资料', items: [{ to: '/developer/regulations', label: '法规中心' }] }];

export default function Layout({ mode }: { mode: Mode }) {
  const location = useLocation(); const nav = mode === 'business' ? businessNav : developerNav;
  return <div className={`app-shell mode-${mode}`}><aside className="app-sidebar"><NavLink to="/" className="brand-lockup"><span className="brand-mark">D</span><span><strong>DataShield</strong><small>智能合规平台</small></span></NavLink><div className="mode-label"><span>{mode === 'business' ? '企业版' : '开发者版'}</span><i /></div><nav className="nav-groups">{nav.map((group) => <div className="nav-group" key={group.section}><div className="nav-section">{group.section}</div>{group.items.map((item) => <NavLink key={item.to} to={item.to} end={item.to === `/${mode}`} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>{item.label}<span>→</span></NavLink>)}</div>)}</nav><div className="sidebar-foot"><div><strong>{mode === 'business' ? '示例科技公司' : '独立开发者'}</strong><small>{mode === 'business' ? '企业工作区' : '开发者工作区'}</small></div><NavLink to="/">切换产品 ↗</NavLink></div></aside><main className="app-main" key={location.pathname}><Outlet /></main></div>;
}
