"""Grounded remediation planning contracts and deterministic renderers."""

from app.tenant.remediation.renderer import (
    build_authoritative_problem_fields,
    build_code_change_plan,
    render_coding_prompt,
)
from app.tenant.remediation.service import (
    RemediationConflictError,
    RemediationNotFoundError,
    RemediationPersistenceError,
    approve_remediation,
    create_remediation,
    get_remediation,
    list_remediations_for_finding,
    load_authoritative_gap_context,
    reject_remediation,
)
from app.tenant.remediation.schemas import (
    AuthoritativeProblemFields,
    CodeChangePlan,
    CodeChangeProposal,
    CodeTestInstruction,
    DocumentChangePlan,
    ProposedDocumentChange,
    RemediationCreateRequest,
    RemediationDecisionRequest,
    RemediationDetail,
    RemediationEvidenceReference,
    RemediationGroundingError,
    RemediationInputSnapshot,
    RemediationListItem,
    RemediationPlanningInput,
    RemediationProductTwinVersionReference,
    RemediationRecord,
    RemediationStatus,
    RemediationType,
    RequestedCodeChange,
    validate_remediation_grounding,
)

__all__ = [
    "AuthoritativeProblemFields",
    "CodeChangePlan",
    "CodeChangeProposal",
    "CodeTestInstruction",
    "DocumentChangePlan",
    "ProposedDocumentChange",
    "RemediationCreateRequest",
    "RemediationDecisionRequest",
    "RemediationDetail",
    "RemediationEvidenceReference",
    "RemediationGroundingError",
    "RemediationInputSnapshot",
    "RemediationListItem",
    "RemediationPlanningInput",
    "RemediationProductTwinVersionReference",
    "RemediationRecord",
    "RemediationStatus",
    "RemediationType",
    "RequestedCodeChange",
    "RemediationConflictError",
    "RemediationNotFoundError",
    "RemediationPersistenceError",
    "approve_remediation",
    "build_authoritative_problem_fields",
    "build_code_change_plan",
    "create_remediation",
    "get_remediation",
    "list_remediations_for_finding",
    "load_authoritative_gap_context",
    "reject_remediation",
    "render_coding_prompt",
    "validate_remediation_grounding",
]
