import { useEffect, useState } from 'react';
import { checkPolicy, generatePolicy, listAssessments, updateProduct } from '../api'; import { useProducts } from '../hooks';
import type { Assessment, PolicyCheckResult, Product } from '../types'; import PageHeader from '../components/PageHeader'; import ErrorBox from '../components/ErrorBox'; import Spinner from '../components/Spinner';
const inputCls='w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-indigo-500';
const answersFrom=(p:Product,a:Assessment|null)=>({...a?.answers,collect_personal:p.collects_personal_data,collect_sensitive:p.collects_sensitive_data,minors_under_14:p.children_related,share_third_party:p.third_party_data_sharing||p.uses_third_party_sdk,third_party_sdks:p.third_party_sdks,privacy_policy:p.has_privacy_policy,storage_location:p.cross_border_data_transfer?'跨境传输到中国境外':(a?.answers.storage_location??'中国境内')});
const payloadFrom=(p:Product,changes:Partial<Product>)=>{const {id,created_at,...payload}= {...p,...changes}; return payload};
export default function PrivacyToolsPage({mode='both'}:{mode?:'generate'|'check'|'both'}){const products=useProducts();const [productId,setProductId]=useState<number|''>('');const [assessment,setAssessment]=useState<Assessment|null>(null);const [generated,setGenerated]=useState('');const [policyText,setPolicyText]=useState('');const [checked,setChecked]=useState<PolicyCheckResult|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const product=products.data?.find((p)=>p.id===productId);
 useEffect(()=>{if(productId===''&&products.data?.length)setProductId(products.data[0].id)},[products.data,productId]);
 useEffect(()=>{if(!product)return;setPolicyText(product.privacy_policy_text||'');listAssessments(product.id).then((x)=>setAssessment(x[0]??null)).catch(()=>setAssessment(null))},[product?.id]);
 const create=async()=>{if(!product)return;setBusy(true);setError(null);try{const result=await generatePolicy({answers:answersFrom(product,assessment),product_name:product.name,company_name:'独立开发者 / 产品运营方',contact:'【联系邮箱】'});setGenerated(result.text);await updateProduct(product.id,payloadFrom(product,{privacy_policy_text:result.text,has_privacy_policy:true}));products.reload()}catch(e:any){setError(e?.response?.data?.detail??e.message)}finally{setBusy(false)}};
 const inspect=async()=>{if(!product||!policyText.trim())return;setBusy(true);setError(null);try{setChecked(await checkPolicy(policyText,product.id));await updateProduct(product.id,payloadFrom(product,{privacy_policy_text:policyText,has_privacy_policy:true}));products.reload()}catch(e:any){setError(e?.response?.data?.detail??e.message)}finally{setBusy(false)}};
 if(products.loading)return <Spinner/>;return <div><PageHeader title={mode==='check'?'隐私政策检查':'隐私政策生成'} desc={mode==='check'?'将政策与 Product Profile 对比，发现行为与披露不一致。':'基于 Product Profile 和最近一次快速检查生成政策草稿。'}/>{error&&<ErrorBox message={error}/>}<section className="bg-white border rounded-xl p-5 mb-6"><label className="block text-sm font-medium mb-2">当前产品</label><select className={inputCls} value={productId} onChange={(e)=>setProductId(Number(e.target.value))}><option value="">请选择产品</option>{(products.data??[]).map((p)=><option key={p.id} value={p.id}>{p.name} · {p.category||'未设置类型'}</option>)}</select></section>
 {!product?<section className="bg-white border rounded-xl p-5">请先在“产品档案”中创建并补充产品信息。</section>:mode!=='check'?<section className="bg-white border rounded-xl p-5"><h2>Generate Privacy Policy</h2><p className="text-sm text-gray-500 mt-2">将读取：{product.name}、{product.category}、{product.target_markets.join(' / ')||'未设置市场'}、数据属性与第三方 SDK。{!assessment&&'尚无快速检查记录，将仅使用产品档案信息。'}</p><button onClick={create} disabled={busy||!product.category} className="mt-4 px-4 py-2 bg-indigo-600 text-white rounded-md text-sm disabled:opacity-50">{busy?'生成中…':'Generate Privacy Policy'}</button>{!product.category&&<p className="text-xs text-red-600 mt-2">请先补充产品类型。</p>}{generated&&<textarea className={`${inputCls} mt-4 font-mono`} rows={24} value={generated} onChange={(e)=>setGenerated(e.target.value)}/>}</section>:<section className="bg-white border rounded-xl p-5"><textarea className={inputCls} rows={14} value={policyText} onChange={(e)=>setPolicyText(e.target.value)} placeholder="粘贴现有隐私政策全文…"/><button onClick={inspect} disabled={busy||!policyText.trim()} className="mt-3 px-4 py-2 bg-indigo-600 text-white rounded-md text-sm disabled:opacity-50">检查政策与产品行为</button>{checked&&<div className="mt-6"><div className="text-3xl font-semibold">{checked.coverage}%</div><p className="text-sm text-gray-500">已覆盖 {checked.covered}/{checked.total} 项</p>{checked.mismatches.length>0&&<section className="mt-5"><h2>Mismatch Found</h2>{checked.mismatches.map((m)=><div key={m.key} className="policy-mismatch"><b>{m.title}</b><p><strong>产品行为：</strong>{m.product_behavior}</p><p><strong>隐私政策：</strong>{m.policy}</p><p><strong>建议：</strong>{m.advice}</p></div>)}</section>}<div className="mt-4 space-y-2">{checked.items.map((item)=><div key={item.name} className={`policy-check-item p-3 rounded-lg border text-sm ${item.covered?'bg-emerald-50 border-emerald-200':'bg-red-50 border-red-200'}`}><b>{item.covered?'✓':'缺失'} {item.name}</b><div className="text-xs mt-1 opacity-75">{item.hint}</div></div>)}</div></div>}</section>}</div>}
