import {BrowserRouter,Navigate,Route,Routes} from 'react-router-dom';
import AppShell from './components/AppShell'; import Layout from './components/Layout';
import ProductSelectorPage from './pages/ProductSelectorPage'; import DashboardPage from './pages/DashboardPage'; import DeveloperHomePage from './pages/DeveloperHomePage'; import CompanyPage from './pages/CompanyPage'; import ProductsPage from './pages/ProductsPage'; import RegulationsPage from './pages/RegulationsPage'; import AnalyzePage from './pages/AnalyzePage'; import ImpactReportPage from './pages/ImpactReportPage'; import SelfAssessmentPage from './pages/SelfAssessmentPage'; import PrivacyToolsPage from './pages/PrivacyToolsPage'; import RiskCenterPage from './pages/RiskCenterPage'; import ActionsPage from './pages/ActionsPage'; import SdkScanPage from './pages/SdkScanPage'; import DeveloperIssuesPage from './pages/DeveloperIssuesPage'; import ReadyToShipPage from './pages/ReadyToShipPage';
import RoutePlaceholder from './pages/new/RoutePlaceholder';
import LandingPage from './pages/new/LandingPage'; import ChooseEditionPage from './pages/new/ChooseEditionPage'; import AuthPage from './pages/new/AuthPage';
import {UnderstandPage,ConfirmPage,ReviewPage} from './pages/new/OnboardingPage';
import TodayPage from './pages/new/TodayPage';
import {FindingsPage,FindingDetailPage} from './pages/new/FindingsPage';
import {ActionsExperience,ActionDetail} from './pages/new/ActionsExperience';
import ProductTwinPage from './pages/new/ProductTwinPage';

const placeholder=(eyebrow:string,title:string,description:string)=><RoutePlaceholder eyebrow={eyebrow} title={title} description={description}/>;
export default function App(){return <BrowserRouter future={{v7_startTransition:true,v7_relativeSplatPath:true}}><Routes>
  <Route path="/" element={<LandingPage/>}/><Route path="/choose" element={<ChooseEditionPage/>}/><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/signup" element={<AuthPage mode="signup"/>}/>
  <Route path="/onboarding" element={<Navigate to="/onboarding/understand" replace/>}/><Route path="/onboarding/understand" element={<UnderstandPage/>}/><Route path="/onboarding/confirm" element={<ConfirmPage/>}/><Route path="/onboarding/review" element={<ReviewPage/>}/>
  <Route path="/app" element={<AppShell/>}><Route index element={<Navigate to="today" replace/>}/><Route path="today" element={<TodayPage/>}/><Route path="monitor" element={placeholder('Monitor',"What's changing",'Regulatory changes and evidence from official sources.')}/><Route path="findings" element={<FindingsPage/>}/><Route path="findings/:id" element={<FindingDetailPage/>}/><Route path="actions" element={<ActionsExperience/>}/><Route path="actions/:id" element={<ActionDetail/>}/><Route path="product" element={<ProductTwinPage/>}/><Route path="settings" element={placeholder('Settings','Workspace settings','Manage this local product experience.')}/></Route>
  <Route path="/legacy" element={<ProductSelectorPage/>}/><Route element={<Layout mode="business"/>}><Route path="/business" element={<DashboardPage/>}/><Route path="/business/company" element={<CompanyPage/>}/><Route path="/business/products" element={<ProductsPage/>}/><Route path="/business/risks" element={<RiskCenterPage/>}/><Route path="/business/check" element={<SelfAssessmentPage/>}/><Route path="/business/impact" element={<AnalyzePage/>}/><Route path="/business/actions" element={<ActionsPage/>}/><Route path="/business/regulations" element={<RegulationsPage/>}/></Route><Route element={<Layout mode="developer"/>}><Route path="/developer" element={<DeveloperHomePage/>}/><Route path="/developer/product" element={<ProductsPage mode="developer"/>}/><Route path="/developer/projects" element={<Navigate to="/developer/product" replace/>}/><Route path="/developer/check" element={<SelfAssessmentPage/>}/><Route path="/developer/sdk-scan" element={<SdkScanPage/>}/><Route path="/developer/policy-check" element={<PrivacyToolsPage mode="check"/>}/><Route path="/developer/policy-generator" element={<PrivacyToolsPage mode="generate"/>}/><Route path="/developer/issues" element={<DeveloperIssuesPage/>}/><Route path="/developer/ready" element={<ReadyToShipPage/>}/><Route path="/developer/regulations" element={<RegulationsPage/>}/></Route><Route path="/report/:id" element={<div className="standalone-report"><ImpactReportPage/></div>}/><Route path="*" element={<Navigate to="/" replace/>}/>
</Routes></BrowserRouter>}
