import {BrowserRouter,Navigate,Route,Routes} from 'react-router-dom';
import AppShell from './components/AppShell'; import Layout from './components/Layout';
import ProductSelectorPage from './pages/ProductSelectorPage'; import DashboardPage from './pages/DashboardPage'; import DeveloperHomePage from './pages/DeveloperHomePage'; import CompanyPage from './pages/CompanyPage'; import ProductsPage from './pages/ProductsPage'; import RegulationsPage from './pages/RegulationsPage'; import AnalyzePage from './pages/AnalyzePage'; import ImpactReportPage from './pages/ImpactReportPage'; import SelfAssessmentPage from './pages/SelfAssessmentPage'; import PrivacyToolsPage from './pages/PrivacyToolsPage'; import RiskCenterPage from './pages/RiskCenterPage'; import ActionsPage from './pages/ActionsPage'; import SdkScanPage from './pages/SdkScanPage'; import DeveloperIssuesPage from './pages/DeveloperIssuesPage'; import ReadyToShipPage from './pages/ReadyToShipPage';
import PublicPlaceholder from './pages/new/PublicPlaceholder'; import RoutePlaceholder from './pages/new/RoutePlaceholder';

const placeholder=(eyebrow:string,title:string,description:string)=><RoutePlaceholder eyebrow={eyebrow} title={title} description={description}/>;
export default function App(){return <BrowserRouter future={{v7_startTransition:true,v7_relativeSplatPath:true}}><Routes>
  <Route path="/" element={<PublicPlaceholder title="Compliance that keeps up with your product." description="DataShield understands what changed, whether it applies, and what you should do next."/>}/>
  <Route path="/choose" element={<PublicPlaceholder title="Choose how DataShield should understand you." description="Start with a product or build a company-wide compliance view." action="/signup"/>}/><Route path="/login" element={<PublicPlaceholder title="Welcome back." description="Continue to your local DataShield workspace." action="/app/today"/>}/><Route path="/signup" element={<PublicPlaceholder title="Create your DataShield workspace." description="Your product setup begins after account creation." action="/onboarding/understand"/>}/>
  <Route path="/onboarding" element={<Navigate to="/onboarding/understand" replace/>}/><Route path="/onboarding/understand" element={<PublicPlaceholder title="Let's understand your product." description="Connect a source or describe the product manually."/>}/><Route path="/onboarding/confirm" element={<PublicPlaceholder title="Here's what we understood." description="Review the first version of your Product Twin."/>}/><Route path="/onboarding/review" element={<PublicPlaceholder title="Your first compliance review." description="DataShield is checking what applies and what needs attention."/>}/>
  <Route path="/app" element={<AppShell/>}><Route index element={<Navigate to="today" replace/>}/><Route path="today" element={placeholder('Today','What needs you now','Review the few decisions DataShield needs from you.')}/><Route path="monitor" element={placeholder('Monitor',"What's changing",'Regulatory changes and evidence from official sources.')}/><Route path="findings" element={placeholder('Findings',"What needs attention",'Evidence-backed gaps that apply to your product.')}/><Route path="findings/:id" element={placeholder('Finding','Review this finding','Understand why it applies and what to do next.')}/><Route path="actions" element={placeholder('Actions',"What we're doing about it",'Review proposed document and code changes.')}/><Route path="actions/:id" element={placeholder('Action','Review recommendation','Approve or reject a grounded recommendation.')}/><Route path="product" element={placeholder('Product Twin','What DataShield knows','A versioned, evidence-backed understanding of your product.')}/><Route path="settings" element={placeholder('Settings','Workspace settings','Manage this local product experience.')}/></Route>
  <Route path="/legacy" element={<ProductSelectorPage/>}/><Route element={<Layout mode="business"/>}><Route path="/business" element={<DashboardPage/>}/><Route path="/business/company" element={<CompanyPage/>}/><Route path="/business/products" element={<ProductsPage/>}/><Route path="/business/risks" element={<RiskCenterPage/>}/><Route path="/business/check" element={<SelfAssessmentPage/>}/><Route path="/business/impact" element={<AnalyzePage/>}/><Route path="/business/actions" element={<ActionsPage/>}/><Route path="/business/regulations" element={<RegulationsPage/>}/></Route><Route element={<Layout mode="developer"/>}><Route path="/developer" element={<DeveloperHomePage/>}/><Route path="/developer/product" element={<ProductsPage mode="developer"/>}/><Route path="/developer/projects" element={<Navigate to="/developer/product" replace/>}/><Route path="/developer/check" element={<SelfAssessmentPage/>}/><Route path="/developer/sdk-scan" element={<SdkScanPage/>}/><Route path="/developer/policy-check" element={<PrivacyToolsPage mode="check"/>}/><Route path="/developer/policy-generator" element={<PrivacyToolsPage mode="generate"/>}/><Route path="/developer/issues" element={<DeveloperIssuesPage/>}/><Route path="/developer/ready" element={<ReadyToShipPage/>}/><Route path="/developer/regulations" element={<RegulationsPage/>}/></Route><Route path="/report/:id" element={<div className="standalone-report"><ImpactReportPage/></div>}/><Route path="*" element={<Navigate to="/" replace/>}/>
</Routes></BrowserRouter>}
