import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {useTranslation} from 'react-i18next';import {getToday,type AttentionItem,type TodayData} from '../../api/intelligence';import {readSession} from '../../features/auth/session';import {readSetup} from '../../features/onboarding/state';
const human=(s:string='')=>s.replace(/_/g,' ');
const humanSummary=(t:any,s:string='')=>s.replace(/NOT_DETECTED\s?/g,t('appnew.findings.humanize.notDetected'));
const typeLabel=(t:any,type:string)=>t(`appnew.today.itemType.${type}`,{defaultValue:human(type)});
const sevLabel=(t:any,s:string)=>t(`appnew.today.severity.${s}`,{defaultValue:s});
const statusLabel=(t:any,s:string)=>t(`appnew.today.itemStatus.${s}`,{defaultValue:human(s)});
function Card({item}:{item:AttentionItem}){const {t}=useTranslation();return <Link to={item.target_route} className="ds-attention"><div><span className={`ds-dot ${item.severity?.toLowerCase()||String(item.type||'').toLowerCase()}`}/><small>{typeLabel(t,item.type)}</small></div><h3>{item.title}</h3><p>{humanSummary(t,item.summary)}</p><footer><span>{item.severity?t('appnew.today.impact',{severity:sevLabel(t,item.severity)}):statusLabel(t,item.status)}</span><b>{t('appnew.today.review')}</b></footer></Link>}
export default function TodayPage(){const {t}=useTranslation();const [data,setData]=useState<TodayData|null>(null);const [error,setError]=useState('');const session=readSession();const setup=readSetup();useEffect(()=>{if(setup)getToday().then(setData).catch((e:any)=>setError(e?.response?.data?.detail||e.message))},[]);if(!setup)return <div className="ds-page"><div className="ds-state"><h2>{t('appnew.today.setupTitle')}</h2><p>{t('appnew.today.setupBody')}</p><Link className="ds-button primary" to="/onboarding/understand">{t('appnew.today.continueSetup')}</Link></div></div>;if(error)return <div className="ds-page"><div className="ds-state error"><h2>{t('appnew.today.loadError')}</h2><p>{error}</p></div></div>;if(!data)return <div className="ds-page"><div className="ds-state"><span className="ds-loader"/><h2>{t('appnew.today.loading')}</h2></div></div>;const needsReview=data.needs_review||[],waitingForYou=data.waiting_for_you||[],recentlyCompleted=data.recently_completed||[];const total=needsReview.length+waitingForYou.length;const fresh=total===0&&recentlyCompleted.length===0;return <div className="ds-page ds-today"><header><span className="ds-eyebrow">{setup?.productName||t('appnew.today.yourWorkspace')}</span><h1>{session?.name?t('appnew.today.greetingNamed',{name:session.name.split(' ')[0]}):t('appnew.today.greeting')}</h1><p>{total?t('appnew.today.needsAttention',{count:total}):t('appnew.today.upToDate')}</p></header>{!total?(fresh?<section className="ds-guide"><span className="ds-eyebrow">{t('appnew.today.guideEyebrow')}</span><h2>{t('appnew.today.guideTitle')}</h2><p>{t('appnew.today.guideLine1')}</p><p>{t('appnew.today.guideLine2')}</p><p>{t('appnew.today.guideLine3')}</p><div className="ds-guide-steps"><Link to="/app/product"><b>1</b><span>{t('appnew.today.guideStep1')}</span></Link><Link to="/app/regulations"><b>2</b><span>{t('appnew.today.guideStep2')}</span></Link><Link to="/onboarding/review"><b>3</b><span>{t('appnew.today.guideStep3')}</span></Link></div><p className="ds-guide-safe"><b>{t('appnew.today.guideSafeTitle')}</b> {t('appnew.today.guideSafeBody')}</p></section>:<section className="ds-caught-up"><div>✓</div><h2>{t('appnew.today.caughtUpTitle')}</h2><p>{t('appnew.today.caughtUpBody')}</p><small>{t('appnew.today.caughtUpNote')}</small></section>):<>{needsReview.length>0&&<Section title={t('appnew.today.needsReview')} items={needsReview}/>} {waitingForYou.length>0&&<Section title={t('appnew.today.waitingForYou')} items={waitingForYou}/>}</>}{recentlyCompleted.length>0&&<Section title={t('appnew.today.recentlyCompleted')} items={recentlyCompleted}/>}{total>0&&<div className="ds-monitor-note"><b>{t('appnew.today.howtoTitle')}</b>{t('appnew.today.howtoBody')}</div>}</div>}
function Section({title,items}:{title:string;items:AttentionItem[]}){return <section className="ds-attention-section"><h2>{title}<span>{items.length}</span></h2><div>{items.map(i=><Card item={i} key={i.id}/>)}</div></section>}
